import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Provider from "@/Components/Provider";
import MobileProvider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div data-theme="dark">
          <ClerkProvider>
            <MobileProvider>
              <Provider>{children}</Provider>
            </MobileProvider>
          </ClerkProvider>
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
